version: '3.7'

services:
  # postgres
  
  psql-latest: &psql
    build: ./test/docker/postgres
    container_name: org-sql-postgres-latest
    restart: 'no'
    environment:    
      - POSTGRES_PASSWORD=toor
      - POSTGRES_USER=root
    ports:
      - 60016:5432

  psql-15:
    <<: *psql
    build:
      context: ./test/docker/postgres
      args:
        IMAGE: postgres:15.8-alpine
    container_name: org-sql-postgres-15
    ports:
      - 60015:5432

  psql-14:
    <<: *psql
    build:
      context: ./test/docker/postgres
      args:
        IMAGE: postgres:14.13-alpine
    container_name: org-sql-postgres-14
    ports:
      - 60014:5432

  psql-13:
    <<: *psql
    build:
      context: ./test/docker/postgres
      args:
        IMAGE: postgres:13.16-alpine
    container_name: org-sql-postgres-13
    ports:
      - 60013:5432

  ## mariadb

  ## ASSUME the mariadb and mysql docker images use the same service config
  mariadb-latest: &mariadb
    build: ./test/docker/mariadb
    container_name: org-sql-mariadb-latest
    restart: 'no'
    environment:    
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - 60114:3306

  mariadb-1011:
    <<: *mariadb
    build:
      context: ./test/docker/mariadb
      args:
        IMAGE: mariadb:10.11.8
    container_name: org-sql-mariadb-1011
    ports:
      - 60111:3306

  mariadb-106:
    <<: *mariadb
    build:
      context: ./test/docker/mariadb
      args:
        IMAGE: mariadb:10.6.18
    container_name: org-sql-mariadb-106
    ports:
      - 60106:3306

  mariadb-105:
    <<: *mariadb
    build:
      context: ./test/docker/mariadb
      args:
        IMAGE: mariadb:10.5.25
    container_name: org-sql-mariadb-105
    ports:
      - 60105:3306
      
  ## mysql

  mysql-latest:
    <<: *mariadb
    build:
      context: ./test/docker/mariadb
      args:
        IMAGE: mysql:8.4.2
    container_name: org-sql-mysql-latest
    ports:
      - 60284:3306

  mysql80:
    <<: *mariadb
    build:
      context: ./test/docker/mariadb
      args:
        IMAGE: mysql:8.0.39
    container_name: org-sql-mysql-80
    ports:
      - 60280:3306

  ## sqlserver

  sqlserver-latest: &sqlserver
    build: ./test/docker/sql-server
    container_name: org-sql-sqlserver-latest
    restart: 'no'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SFDwIcGvZdx&9g1f4Uy
    ports:
      - 60322:1433

  sqlserver-2019:
    <<: *sqlserver
    container_name: org-sql-sqlserver-2019
    build:
      context: ./test/docker/sql-server
      args:
        IMAGE: mcr.microsoft.com/mssql/server:2019-CU27-ubuntu-20.04
    ports:
      - 60319:1433

  sqlserver-2017:
    <<: *sqlserver
    container_name: org-sql-sqlserver-2017
    build:
      context: ./test/docker/sql-server
      args:
        IMAGE: mcr.microsoft.com/mssql/server:2017-CU29-ubuntu-16.04
    ports:
      - 60317:1433
