name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '29_3'
    steps:
    - uses: mamba-org/setup-micromamba@v1.9.0
      with:
        micromamba-version: '1.5.6-0'
        environment-file: env-${{ matrix.emacs_version }}.yml
        cache-environment: true
        post-cleanup: 'all'

    - name: Setup testing databases
      run: docker-compose up -d

    - name: Run tests
      shell: micromamba-shell {0}
      run: |
        export LD_PRELOAD=/usr/lib/libc_malloc_debug.so
        make install
        make
