name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '29.3'
    steps:
    - uses: actions/checkout@v2

    - uses: mamba-org/setup-micromamba@v1.9.0
      with:
        micromamba-version: '1.5.6-0'
        environment-file: env-${{ matrix.emacs_version }}.yml
        cache-environment: true
        post-cleanup: 'all'

    - uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        up-flags: "--build"
        down-flags: "--volumes"

    - name: Run tests
      shell: micromamba-shell {0}
      run: |
        export LD_PRELOAD=/usr/lib/libc_malloc_debug.so
        make install
        make
