name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '29.3'
    steps:
    - uses: mamba-org/setup-micromamba@v1
      with:
        version: '1.9.0'
        micromamba-version: '1.5.8-0'
        environment-file: env-${{ matrix.emacs_version }}.yml
        init-shell: >-
          bash
        cache-environment: true
        post-cleanup: 'all'

    - name: Setup testing databases
      run: docker-compose up -d

    - name: Run tests
      run: |
        export LD_PRELOAD=/usr/lib/libc_malloc_debug.so
        make install
        make
